export default {
  "clickhouse": "to Clickhouse",
  "duckdb": "to DuckDB",
  "fabric": "to Microsoft Fabric",
  "iceberg": "to Iceberg",
  "memgraph": "to Memgraph",
  "mongodb": "to MongoDB",
  "neo4j": "to Neo4j",
  "oracle": "to Oracle",
  "postgres": "to PostgreSQL",
  "mysql": "to MySQL",
  "sqlserver": "to SQL Server",
  "pinot": "to Pinot",
  "snowflake": "to Snowflake",
}
