export default {
  "index": "Home",
  "getting-started": "Getting started",
  "client-libraries": "Client libraries",
  "ai-ecosystem": "AI ecosystem",
  "fundamentals": "Fundamentals",
  "data-modeling": "Data modeling",
  "data-migration": "Data migration",
  "querying": "Querying",
  "advanced-algorithms": "Advanced algorithms",
  "custom-query-modules": "Custom query modules",
  "data-visualization": "Data visualization",
  "database-management": "Database management",
  "deployment": "Deployment",
  "clustering": "Clustering",
  "data-streams": "Data streams",
  "help-center": "Help center",
  "release-notes": "Release notes",
  "memgraph-in-production": "Memgraph in production"
}