export default {
    "collections": "Collections",
    "csv-file-import": "CSV file import",
    "custom-configuration": "Custom configuration",
    "data-modeling": "Data modeling",
    "graphchat": "GraphChat",
    "graph-schema": "Graph schema",
    "graph-style-script": "Graph Style Script (GSS)",
    "layout": "Layout",
    "logs": "Logs",
    "multi-tenancy": "Multi-tenancy",
    "monitoring": "Monitoring",
    "run-history": "Run history",
    "sharing-features": "Sharing features",
    "single-sign-on": "Single sign-on",
  }