export default {
  "alter": "ALTER",
  "call": "CALL",
  "case": "CASE",
  "create": "CREATE",
  "delete": "DELETE",
  "drop": "DROP",
  "explain": "EXPLAIN",
  "foreach": "FOREACH",
  "load-csv": "LOAD CSV",
  "load-parquet": "LOAD PARQUET",
  "match": "MATCH",
  "merge": "MERGE",
  "optional-match": "OPTIONAL MATCH",
  "profile": "PROFILE",
  "remove": "REMOVE",
  "return": "RETURN",
  "set": "SET",
  "union": "UNION",
  "unwind": "UNWIND",
  "using-parallel-execution": "USING PARALLEL EXECUTION",
  "where": "WHERE",
  "with": "WITH"
}
