export default {
  "alter": "ALTER",
  "call": "CALL",
  "case": "CASE",
  "create": "CREATE",
  "delete": "DELETE",
  "drop-all-constraints": "DROP ALL CONSTRAINTS",
  "drop-all-indexes": "DROP ALL INDEXES",
  "drop-graph": "DROP GRAPH",
  "explain": "EXPLAIN",
  "foreach": "FOREACH",
  "load-csv": "LOAD CSV",
  "match": "MATCH",
  "merge": "MERGE",
  "optional-match": "OPTIONAL MATCH",
  "profile": "PROFILE",
  "remove": "REMOVE",
  "return": "RETURN",
  "set": "SET",
  "union": "UNION",
  "unwind": "UNWIND",
  "where": "WHERE",
  "with": "WITH"
}
