name: Create Issue on Release PR Merge

on:
  pull_request:
    types: [closed]
    
jobs:
  create_issue:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.base.ref, 'main') # Only when merged to main
    runs-on: ubuntu-latest

    steps:
      - name: Check for Specific Label
        id: label_check
        run: |
          LABEL_FOUND=$(echo "${{ github.event.pull_request.labels[*].name }}" | grep -c "release-pr")
          echo "label_found=$LABEL_FOUND" >> $GITHUB_ENV

      - name: Create GitHub Issue
        if: env.label_found == '1'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: issue } = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Update hardcoded Memgraph versions under Getting Started`,
              body: `This issue was automatically created after PR #${{ github.event.pull_request.number }}. https://www.notion.so/memgraph/WIP-Documentation-branching-and-release-strategy-814417bb95ae45848071f535013d3d83?pvs=4#10b6b158b981801c9f0cc43f9f122462`
              assignees: ["katarinasupe"]
            });
            console.log(`Created issue: ${issue.html_url}`);
